name: Pipeline-gui

on:
    workflow_dispatch:
    push:
        paths:
            - "**.cpp"
            - "gui/**"
    pull_request:
        paths:
            - "**.cpp"
            - "gui/**"

jobs:
    commits:
        name: Commits
        uses: ./.github/workflows/conventional-commits.yml
    coding-style:
        name: Coding-style
        uses: ./.github/workflows/coding-style.yml
