name: "Rust ci"
on:
    workflow_dispatch:
    workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: --deny warnings

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [self-hosted]
        rust: [stable]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run Rust ci
        run: sudo bash devops-scripts/install-rust.sh

  clean:
    needs: unit-tests
    uses: ./.github/workflows/cleanup.yml
