name: 'tests'

on:
  push:
    branches:
    - main
    - master
  pull_request:
    branches:
    - main
    - master

jobs:
    run_tests:
        name: "runs tests bc that's what heroes do"
        runs-on: ubuntu-latest
        container:
          image: epitechcontent/epitest-docker:latest
        steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
          - run: make tests_run
            timeout-minutes: 2
