name: 'zappy'

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - master

env:
  MIRROR_URL: "git@github.com:EpitechPromo2027/B-YEP-400-PAR-4-1-zappy-alexandre.vigoureux.git"

jobs:
  push_to_mirror:
    name: "Push to mirror"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
